'use strict';
/* ============================================================================
 * FUSION-NAMES.JS — curated thematic names for every fusion pair.
 * One entry per unordered family pair (and self-pairs): 903 total.
 * Key format: familyKeyA|familyKeyB in FAMILY_KEYS order.
 * ==========================================================================*/
const FUSION_NAMES = {
  "bullets|bullets": "Infinite Volley",
  "bullets|chase": "Seeker Swarm",
  "bullets|pierce": "Lancer Volley",
  "bullets|bounce": "Ricochet Swarm",
  "bullets|rapid": "Lead Monsoon",
  "bullets|big": "Titan Volley",
  "bullets|split": "Fragment Barrage",
  "bullets|crit": "Killshot Salvo",
  "bullets|orbitals": "Sawblade Salvo",
  "bullets|nova": "Starburst Volley",
  "bullets|laser": "Photon Fusillade",
  "bullets|lifesteal": "Vampire Volley",
  "bullets|shield": "Bulwark Volley",
  "bullets|vitality": "Lifeblood Salvo",
  "bullets|regen": "Vital Volley",
  "bullets|ghost": "Phantom Fusillade",
  "bullets|speed": "Strafe Storm",
  "bullets|magnet": "Lodestone Salvo",
  "bullets|slow": "Stasis Salvo",
  "bullets|bomb": "Cinder Salvo",
  "bullets|rear": "Parting Salvo",
  "bullets|side": "Broadside Hail",
  "bullets|arc": "Voltaic Spray",
  "bullets|cull": "Firing Squad",
  "bullets|velocity": "Railstorm",
  "bullets|thorns": "Needle Reprisal",
  "bullets|armor": "Ironclad Barrage",
  "bullets|dodge": "Phantom Fusillade",
  "bullets|scavenger": "Harvest Volley",
  "bullets|greed": "Bounty Barrage",
  "bullets|adrenaline": "Panic Salvo",
  "bullets|shrink": "Needlepoint Barrage",
  "bullets|drones": "Echo Squadron",
  "bullets|missiles": "Warhead Barrage",
  "bullets|mortar": "Cluster Hail",
  "bullets|boom": "Cluster Barrage",
  "bullets|frost": "Hailstorm",
  "bullets|impact": "Concussive Salvo",
  "bullets|turret": "Firing Line",
  "bullets|vortex": "Riftstorm Volley",
  "bullets|graze": "Brushfire Volley",
  "bullets|ram": "Cannonade Rush",
  "chase|chase": "Apex Predator",
  "chase|pierce": "Seeker Lance",
  "chase|bounce": "Ricochet Hound",
  "chase|rapid": "Seeker Frenzy",
  "chase|big": "Homing Haymaker",
  "chase|split": "Seeker Shrapnel",
  "chase|crit": "Headhunter Rounds",
  "chase|orbitals": "Hunting Halo",
  "chase|nova": "Seeker Bloom",
  "chase|laser": "Serpent Beam",
  "chase|lifesteal": "Vampire Seekers",
  "chase|shield": "Warded Pursuit",
  "chase|vitality": "Heartseeker",
  "chase|regen": "Hunter's Vigor",
  "chase|ghost": "Phantom Pursuit",
  "chase|speed": "Pursuit Drive",
  "chase|magnet": "Gravity Hound",
  "chase|slow": "Predator's Web",
  "chase|bomb": "Hellhound Rounds",
  "chase|rear": "Hunter's Wake",
  "chase|side": "Pincer Pursuit",
  "chase|arc": "Stormchaser",
  "chase|cull": "Guided Guillotine",
  "chase|velocity": "Peregrine Rounds",
  "chase|thorns": "Vengeful Swarm",
  "chase|armor": "Ironclad Hunter",
  "chase|dodge": "Phantom Pursuit",
  "chase|scavenger": "Bloodhound Harvest",
  "chase|greed": "Bounty Hunter",
  "chase|adrenaline": "Frenzied Hunt",
  "chase|shrink": "Wisp Hunter",
  "chase|drones": "Wolfpack Wing",
  "chase|missiles": "Total Lock-On",
  "chase|mortar": "Smart Shellfire",
  "chase|boom": "Smart Bombs",
  "chase|frost": "Cold Pursuit",
  "chase|impact": "Seeker Slam",
  "chase|turret": "Bloodhound Battery",
  "chase|vortex": "Hungering Spiral",
  "chase|graze": "Daredevil Homing",
  "chase|ram": "Bloodhound Charge",
  "pierce|pierce": "Voidpiercer",
  "pierce|bounce": "Ricochet Lance",
  "pierce|rapid": "Needle Storm",
  "pierce|big": "Titan Lance",
  "pierce|split": "Splinter Lance",
  "pierce|crit": "Lethal Lancet",
  "pierce|orbitals": "Sawblade Lance",
  "pierce|nova": "Starburst Lance",
  "pierce|laser": "Photon Javelin",
  "pierce|lifesteal": "Vampiric Needle",
  "pierce|shield": "Bulwark Lance",
  "pierce|vitality": "Ironheart Impaler",
  "pierce|regen": "Mending Javelin",
  "pierce|ghost": "Spectral Skewer",
  "pierce|speed": "Javelin Dash",
  "pierce|magnet": "Prospector's Pike",
  "pierce|slow": "Stasis Needle",
  "pierce|bomb": "Branding Iron",
  "pierce|rear": "Tailspike",
  "pierce|side": "Broadside Skewer",
  "pierce|arc": "Lightning Rod",
  "pierce|cull": "Impaler's Edict",
  "pierce|velocity": "Railspike",
  "pierce|thorns": "Quill Reprisal",
  "pierce|armor": "Adamant Skewer",
  "pierce|dodge": "Wraith Needle",
  "pierce|scavenger": "Reaper's Skewer",
  "pierce|greed": "Prospector's Drill",
  "pierce|adrenaline": "Spiteful Spear",
  "pierce|shrink": "Needlepoint",
  "pierce|drones": "Impaler Escort",
  "pierce|missiles": "Bunker Buster",
  "pierce|mortar": "Bunker Buster",
  "pierce|boom": "Bunker Buster",
  "pierce|frost": "Icicle Impaler",
  "pierce|impact": "Battering Bolt",
  "pierce|turret": "Railgun Nests",
  "pierce|vortex": "Riftlance",
  "pierce|graze": "Threadneedle",
  "pierce|ram": "Bayonet Charge",
  "bounce|bounce": "Infinite Ricochet",
  "bounce|rapid": "Pinball Frenzy",
  "bounce|big": "Wrecking Ricochet",
  "bounce|split": "Ricochet Burst",
  "bounce|crit": "Lucky Ricochet",
  "bounce|orbitals": "Ricochet Halo",
  "bounce|nova": "Ricochet Bloom",
  "bounce|laser": "Prism Ricochet",
  "bounce|lifesteal": "Leeching Rebound",
  "bounce|shield": "Rebound Aegis",
  "bounce|vitality": "Vital Rebound",
  "bounce|regen": "Mending Rebound",
  "bounce|ghost": "Spectral Rebound",
  "bounce|speed": "Pinball Protocol",
  "bounce|magnet": "Pinball Payday",
  "bounce|slow": "Molasses Rebound",
  "bounce|bomb": "Pinball Inferno",
  "bounce|rear": "Bank Shot Barrage",
  "bounce|side": "Pinball Broadside",
  "bounce|arc": "Pinball Lightning",
  "bounce|cull": "Grim Ricochet",
  "bounce|velocity": "Hypersonic Rebound",
  "bounce|thorns": "Spiteful Rebound",
  "bounce|armor": "Deflection Plating",
  "bounce|dodge": "Phantom Carom",
  "bounce|scavenger": "Lucky Rebound",
  "bounce|greed": "Jackpot Ricochet",
  "bounce|adrenaline": "Rebound Rush",
  "bounce|shrink": "Pinball Wisp",
  "bounce|drones": "Carom Convoy",
  "bounce|missiles": "Ricochet Warheads",
  "bounce|mortar": "Bouncing Betty",
  "bounce|boom": "Bouncing Betty",
  "bounce|frost": "Glacial Rebound",
  "bounce|impact": "Kinetic Carom",
  "bounce|turret": "Bank-Shot Battery",
  "bounce|vortex": "Riptide Rebound",
  "bounce|graze": "Lucky Ricochet",
  "bounce|ram": "Pinball Bruiser",
  "rapid|rapid": "Infinite Trigger",
  "rapid|big": "Autocannon",
  "rapid|split": "Flakstorm",
  "rapid|crit": "Lethal Cadence",
  "rapid|orbitals": "Sawblade Cyclone",
  "rapid|nova": "Pulsar Overdrive",
  "rapid|laser": "Gatling Beam",
  "rapid|lifesteal": "Vampire Gatling",
  "rapid|shield": "Suppressive Aegis",
  "rapid|vitality": "Heartbeat Trigger",
  "rapid|regen": "Heartbeat Trigger",
  "rapid|ghost": "Phantom Trigger",
  "rapid|speed": "Overclock",
  "rapid|magnet": "Quickdraw Prospector",
  "rapid|slow": "Bullet Time",
  "rapid|bomb": "Flamethrower",
  "rapid|rear": "Parthian Tempo",
  "rapid|side": "Broadside Blitz",
  "rapid|arc": "Voltaic Barrage",
  "rapid|cull": "Gatling Guillotine",
  "rapid|velocity": "Full Throttle",
  "rapid|thorns": "Wildfire Trigger",
  "rapid|armor": "Ironclad Trigger",
  "rapid|dodge": "Trigger Blur",
  "rapid|scavenger": "Feeding Frenzy",
  "rapid|greed": "Coin-Op Cannon",
  "rapid|adrenaline": "Redline Reflex",
  "rapid|shrink": "Hummingbird Fury",
  "rapid|drones": "Swarm Cadence",
  "rapid|missiles": "Rocket Deluge",
  "rapid|mortar": "Saturation Fire",
  "rapid|boom": "Full-Auto Fireworks",
  "rapid|frost": "Gatling Glacier",
  "rapid|impact": "Jackhammer",
  "rapid|turret": "Gatling Garrison",
  "rapid|vortex": "Maelstrom Barrage",
  "rapid|graze": "Deathwish Tempo",
  "rapid|ram": "Blitz Prow",
  "big|big": "Planet Cracker",
  "big|split": "Frag Cannon",
  "big|crit": "Megaton Jackpot",
  "big|orbitals": "Titan's Halo",
  "big|nova": "Supernova Shells",
  "big|laser": "Siege Beam",
  "big|lifesteal": "Vampire Cannonball",
  "big|shield": "Bulwark Cannon",
  "big|vitality": "Behemoth Caliber",
  "big|regen": "Titan's Pulse",
  "big|ghost": "Phantom Howitzer",
  "big|speed": "Juggernaut Sprint",
  "big|magnet": "Gravity Slugs",
  "big|slow": "Crushing Stasis",
  "big|bomb": "Meteor Shells",
  "big|rear": "Parting Cannonball",
  "big|side": "Broadside Bruiser",
  "big|arc": "Thunderhead Slugs",
  "big|cull": "Headsman's Maul",
  "big|velocity": "Cannonball Express",
  "big|thorns": "Meteor Mantle",
  "big|armor": "Juggernaut Rounds",
  "big|dodge": "Phantom Howitzer",
  "big|scavenger": "Harvest Howitzer",
  "big|greed": "Jackpot Slugs",
  "big|adrenaline": "Payback Howitzer",
  "big|shrink": "Pocket Artillery",
  "big|drones": "Siege Squadron",
  "big|missiles": "Titan Warheads",
  "big|mortar": "Blockbuster Shells",
  "big|boom": "Warhead Slugs",
  "big|frost": "Glacier Shells",
  "big|impact": "Wrecking Ball",
  "big|turret": "Siege Battery",
  "big|vortex": "Singularity Shells",
  "big|graze": "Daredevil Ordnance",
  "big|ram": "Juggernaut Rounds",
  "split|split": "Fission Cascade",
  "split|crit": "Shrapnel Storm",
  "split|orbitals": "Shredder Halo",
  "split|nova": "Shrapnel Supernova",
  "split|laser": "Prism Shatter",
  "split|lifesteal": "Crimson Shrapnel",
  "split|shield": "Shrapnel Aegis",
  "split|vitality": "Blooming Burst",
  "split|regen": "Mitosis Rounds",
  "split|ghost": "Wraith Fragments",
  "split|speed": "Scattersprint",
  "split|magnet": "Bounty Burst",
  "split|slow": "Stasis Shrapnel",
  "split|bomb": "Cinder Burst",
  "split|rear": "Parting Gift",
  "split|side": "Winged Shrapnel",
  "split|arc": "Voltaic Shrapnel",
  "split|cull": "Reaper's Burst",
  "split|velocity": "Hypersonic Shrapnel",
  "split|thorns": "Frag Reprisal",
  "split|armor": "Flak Jacket",
  "split|dodge": "Shatterstep",
  "split|scavenger": "Harvest Burst",
  "split|greed": "Jackpot Burst",
  "split|adrenaline": "Frenzy Fragments",
  "split|shrink": "Splinter Cell",
  "split|drones": "Shrapnel Squadron",
  "split|missiles": "Cluster Warheads",
  "split|mortar": "Clusterburst",
  "split|boom": "Frag Cascade",
  "split|frost": "Shatterfrost",
  "split|impact": "Concussion Cluster",
  "split|turret": "Shrapnel Sentry",
  "split|vortex": "Singularity Shards",
  "split|graze": "Daredevil Shards",
  "split|ram": "Demolition Derby",
  "crit|crit": "Deadeye Ascendant",
  "crit|orbitals": "Razor Roulette",
  "crit|nova": "Supernova Strike",
  "crit|laser": "Deadeye Beam",
  "crit|lifesteal": "Vampiric Deathblow",
  "crit|shield": "Assassin's Bulwark",
  "crit|vitality": "Vital Strike",
  "crit|regen": "Surgeon's Pulse",
  "crit|ghost": "Phantom Edge",
  "crit|speed": "Lightning Gambit",
  "crit|magnet": "Lucky Lodestone",
  "crit|slow": "Bullet Time",
  "crit|bomb": "Flashpoint",
  "crit|rear": "Parting Blow",
  "crit|side": "Flanking Deathblow",
  "crit|arc": "Thunderstruck",
  "crit|cull": "Headsman's Luck",
  "crit|velocity": "Killshot Express",
  "crit|thorns": "Vicious Reprisal",
  "crit|armor": "Plated Precision",
  "crit|dodge": "Untouchable Edge",
  "crit|scavenger": "Butcher's Bounty",
  "crit|greed": "Jackpot Strike",
  "crit|adrenaline": "Berserker's Eye",
  "crit|shrink": "Pinpoint Lethality",
  "crit|drones": "Assassin Squadron",
  "crit|missiles": "Warhead Roulette",
  "crit|mortar": "Killshot Crater",
  "crit|boom": "Overkill Warhead",
  "crit|frost": "Shatterpoint",
  "crit|impact": "Haymaker",
  "crit|turret": "Sniper Nest",
  "crit|vortex": "Ruinous Singularity",
  "crit|graze": "Daredevil's Edge",
  "crit|ram": "Jackpot Slam",
  "orbitals|orbitals": "Ring of Ruin",
  "orbitals|nova": "Blade Corona",
  "orbitals|laser": "Photon Halo",
  "orbitals|lifesteal": "Leech Halo",
  "orbitals|shield": "Bladed Bulwark",
  "orbitals|vitality": "Lifeblade Halo",
  "orbitals|regen": "Halo of Renewal",
  "orbitals|ghost": "Spectral Sawblades",
  "orbitals|speed": "Sawblade Comet",
  "orbitals|magnet": "Harvester Halo",
  "orbitals|slow": "Stasis Grinder",
  "orbitals|bomb": "Cinder Carousel",
  "orbitals|rear": "Tailspin Scythes",
  "orbitals|side": "Bladewing Broadside",
  "orbitals|arc": "Tesla Sawblades",
  "orbitals|cull": "Reaper's Carousel",
  "orbitals|velocity": "Razor Cyclone",
  "orbitals|thorns": "Razorwire Aura",
  "orbitals|armor": "Bladed Bastion",
  "orbitals|dodge": "Mirage Rotors",
  "orbitals|scavenger": "Harvest Halo",
  "orbitals|greed": "Fortune's Whirl",
  "orbitals|adrenaline": "Rage Carousel",
  "orbitals|shrink": "Pinpoint Halo",
  "orbitals|drones": "Bladed Retinue",
  "orbitals|missiles": "Satellite Strike",
  "orbitals|mortar": "Ring of Ruin",
  "orbitals|boom": "Blastwheel",
  "orbitals|frost": "Frostmill",
  "orbitals|impact": "Repulsor Blades",
  "orbitals|turret": "Sentry Halo",
  "orbitals|vortex": "Maelstrom Blades",
  "orbitals|graze": "Razor's Edge",
  "orbitals|ram": "Buzzsaw Charge",
  "nova|nova": "Supernova",
  "nova|laser": "Supernova Lance",
  "nova|lifesteal": "Sanguine Starburst",
  "nova|shield": "Bulwark Burst",
  "nova|vitality": "Heartburst",
  "nova|regen": "Lifebloom Pulse",
  "nova|ghost": "Phoenix Pulse",
  "nova|speed": "Slipstream Starburst",
  "nova|magnet": "Gravity Flare",
  "nova|slow": "Stasis Bloom",
  "nova|bomb": "Solar Flare",
  "nova|rear": "Parting Supernova",
  "nova|side": "Compass Rose",
  "nova|arc": "Tesla Bloom",
  "nova|cull": "Death Knell",
  "nova|velocity": "Hypernova",
  "nova|thorns": "Solar Retribution",
  "nova|armor": "Ironburst",
  "nova|dodge": "Mirage Corona",
  "nova|scavenger": "Reaper's Radiance",
  "nova|greed": "Midas Flare",
  "nova|adrenaline": "Retaliation Burst",
  "nova|shrink": "Pinpoint Pulsar",
  "nova|drones": "Starburst Squadron",
  "nova|missiles": "Starburst Salvo",
  "nova|mortar": "Shockwave Corona",
  "nova|boom": "Blastwave Bloom",
  "nova|frost": "Permafrost Pulse",
  "nova|impact": "Shockwave Bloom",
  "nova|turret": "Sentry Starburst",
  "nova|vortex": "Event Horizon",
  "nova|graze": "Daredevil Pulse",
  "nova|ram": "Starcrash",
  "laser|laser": "Godbeam",
  "laser|lifesteal": "Vampiric Ray",
  "laser|shield": "Beam Bastion",
  "laser|vitality": "Vital Ray",
  "laser|regen": "Photosynthesis",
  "laser|ghost": "Afterlife Beam",
  "laser|speed": "Photon Dash",
  "laser|magnet": "Tractor Beam",
  "laser|slow": "Tractor Beam",
  "laser|bomb": "Scorchbeam",
  "laser|rear": "Backscatter Beam",
  "laser|side": "Trident Beam",
  "laser|arc": "Ion Cascade",
  "laser|cull": "Guillotine Ray",
  "laser|velocity": "Lightspeed Lance",
  "laser|thorns": "Vengeance Ray",
  "laser|armor": "Bastion Beam",
  "laser|dodge": "Blinkbeam",
  "laser|scavenger": "Harvester Ray",
  "laser|greed": "Avarice Ray",
  "laser|adrenaline": "Overdrive Lance",
  "laser|shrink": "Pinhole Lance",
  "laser|drones": "Prism Escort",
  "laser|missiles": "Guided Sunlance",
  "laser|mortar": "Plasma Artillery",
  "laser|boom": "Detonation Ray",
  "laser|frost": "Cryo Lance",
  "laser|impact": "Repulsor Beam",
  "laser|turret": "Beam Battery",
  "laser|vortex": "Singularity Beam",
  "laser|graze": "Tightrope Ray",
  "laser|ram": "Searing Charge",
  "lifesteal|lifesteal": "Exsanguinate",
  "lifesteal|shield": "Blood Ward",
  "lifesteal|vitality": "Heartdrinker",
  "lifesteal|regen": "Eternal Thirst",
  "lifesteal|ghost": "Wraith Feast",
  "lifesteal|speed": "Bloodrush",
  "lifesteal|magnet": "Siphon Field",
  "lifesteal|slow": "Leeching Mire",
  "lifesteal|bomb": "Cauterize",
  "lifesteal|rear": "Vampire's Wake",
  "lifesteal|side": "Leeching Broadside",
  "lifesteal|arc": "Vampiric Voltage",
  "lifesteal|cull": "Soul Harvest",
  "lifesteal|velocity": "Blood Torrent",
  "lifesteal|thorns": "Blood Barrier",
  "lifesteal|armor": "Bloodplate",
  "lifesteal|dodge": "Phantom Feast",
  "lifesteal|scavenger": "Carrion Feast",
  "lifesteal|greed": "Glutton's Bounty",
  "lifesteal|adrenaline": "Bloodrush",
  "lifesteal|shrink": "Sanguine Sliver",
  "lifesteal|drones": "Leech Squadron",
  "lifesteal|missiles": "Leech Warheads",
  "lifesteal|mortar": "Crimson Rain",
  "lifesteal|boom": "Carnage Harvest",
  "lifesteal|frost": "Cold Hunger",
  "lifesteal|impact": "Vampiric Haymaker",
  "lifesteal|turret": "Leech Battery",
  "lifesteal|vortex": "Devouring Maw",
  "lifesteal|graze": "Vampire's Waltz",
  "lifesteal|ram": "Vampire Lunge",
  "shield|shield": "Absolute Aegis",
  "shield|vitality": "Heartguard",
  "shield|regen": "Aegis Renewal",
  "shield|ghost": "Spectral Aegis",
  "shield|speed": "Bulwark Sprint",
  "shield|magnet": "Deflector Array",
  "shield|slow": "Stasis Bulwark",
  "shield|bomb": "Cinder Aegis",
  "shield|rear": "Covered Retreat",
  "shield|side": "Broadside Aegis",
  "shield|arc": "Tesla Bulwark",
  "shield|cull": "Warden's Verdict",
  "shield|velocity": "Kinetic Bastion",
  "shield|thorns": "Scorching Aegis",
  "shield|armor": "Fortress Plating",
  "shield|dodge": "Mirage Bulwark",
  "shield|scavenger": "Salvage Barrier",
  "shield|greed": "Gilded Aegis",
  "shield|adrenaline": "Rage Plating",
  "shield|shrink": "Thimble Aegis",
  "shield|drones": "Escort Phalanx",
  "shield|missiles": "Bastion Salvo",
  "shield|mortar": "Bastion Barrage",
  "shield|boom": "Detonation Ward",
  "shield|frost": "Glacier Guard",
  "shield|impact": "Battering Bulwark",
  "shield|turret": "Fortress Protocol",
  "shield|vortex": "Maelstrom Mantle",
  "shield|graze": "Whisker Ward",
  "shield|ram": "Battering Bulwark",
  "vitality|vitality": "Immortal Heart",
  "vitality|regen": "Immortal Core",
  "vitality|ghost": "Undying Echo",
  "vitality|speed": "Marathon Heart",
  "vitality|magnet": "Lodestone Heart",
  "vitality|slow": "Colossus Field",
  "vitality|bomb": "Phoenix Heart",
  "vitality|rear": "Hearty Backlash",
  "vitality|side": "Ironside",
  "vitality|arc": "Galvanic Heart",
  "vitality|cull": "Heartstopper",
  "vitality|velocity": "Pulse Accelerator",
  "vitality|thorns": "Barbed Heart",
  "vitality|armor": "Ironheart",
  "vitality|dodge": "Charmed Life",
  "vitality|scavenger": "Carrion Comfort",
  "vitality|greed": "Gilded Vigor",
  "vitality|adrenaline": "Berserker Vigor",
  "vitality|shrink": "Compact Titan",
  "vitality|drones": "Guardian Flock",
  "vitality|missiles": "Juggernaut Salvo",
  "vitality|mortar": "Titan Shells",
  "vitality|boom": "Vigor Warhead",
  "vitality|frost": "Glacial Fortitude",
  "vitality|impact": "Heavyweight Punch",
  "vitality|turret": "Fortress Heart",
  "vitality|vortex": "Devouring Heart",
  "vitality|graze": "Braveheart",
  "vitality|ram": "Ironhide Charge",
  "regen|regen": "Undying Wellspring",
  "regen|ghost": "Spectral Mending",
  "regen|speed": "Second Wind",
  "regen|magnet": "Lodestone Bloom",
  "regen|slow": "Sanctuary Bubble",
  "regen|bomb": "Phoenix Blood",
  "regen|rear": "Healing Wake",
  "regen|side": "Mending Broadside",
  "regen|arc": "Galvanic Mending",
  "regen|cull": "Reaper's Respite",
  "regen|velocity": "Vital Momentum",
  "regen|thorns": "Briar Heart",
  "regen|armor": "Living Plating",
  "regen|dodge": "Untouchable Mend",
  "regen|scavenger": "Wellspring",
  "regen|greed": "Compound Interest",
  "regen|adrenaline": "Second Wind Surge",
  "regen|shrink": "Tardigrade Mode",
  "regen|drones": "Medic Escort",
  "regen|missiles": "Medic's Arsenal",
  "regen|mortar": "Lifespring Shells",
  "regen|boom": "Bombshell Bloom",
  "regen|frost": "Cryotherapy",
  "regen|impact": "Healing Haymaker",
  "regen|turret": "Repair Garrison",
  "regen|vortex": "Healing Maelstrom",
  "regen|graze": "Razor's Respite",
  "regen|ram": "Troll Charge",
  "ghost|ghost": "Poltergeist",
  "ghost|speed": "Spectral Dash",
  "ghost|magnet": "Spirit Siphon",
  "ghost|slow": "Purgatory Drift",
  "ghost|bomb": "Wraithfire",
  "ghost|rear": "Poltergeist Volley",
  "ghost|side": "Spectral Broadside",
  "ghost|arc": "Ethereal Voltage",
  "ghost|cull": "Grim Reaper",
  "ghost|velocity": "Wraithshot",
  "ghost|thorns": "Vengeful Wraith",
  "ghost|armor": "Wraithplate",
  "ghost|dodge": "Untouchable",
  "ghost|scavenger": "Grave Robber",
  "ghost|greed": "Grave Robber",
  "ghost|adrenaline": "Vengeful Spirit",
  "ghost|shrink": "Will-o'-Wisp",
  "ghost|drones": "Haunted Escort",
  "ghost|missiles": "Poltergeist Payload",
  "ghost|mortar": "Poltergeist Shells",
  "ghost|boom": "Poltergeist Payload",
  "ghost|frost": "Cold Shoulder",
  "ghost|impact": "Poltergeist Punch",
  "ghost|turret": "Haunted Battery",
  "ghost|vortex": "Wraithgate",
  "ghost|graze": "Deathdancer",
  "ghost|ram": "Juggernaut Wraith",
  "speed|speed": "Blur Drive",
  "speed|magnet": "Comet Collector",
  "speed|slow": "Bullet Time",
  "speed|bomb": "Afterburner",
  "speed|rear": "Hit and Run",
  "speed|side": "Strafing Run",
  "speed|arc": "Lightning Stride",
  "speed|cull": "Blitz Reaper",
  "speed|velocity": "Slipstream Rounds",
  "speed|thorns": "Stinging Slipstream",
  "speed|armor": "Juggernaut Dash",
  "speed|dodge": "Untouchable Blur",
  "speed|scavenger": "Swift Harvest",
  "speed|greed": "Gold Rush",
  "speed|adrenaline": "Flight Response",
  "speed|shrink": "Hummingbird",
  "speed|drones": "Falcon Escort",
  "speed|missiles": "Afterburner Salvo",
  "speed|mortar": "Strafing Run",
  "speed|boom": "Nitro Rounds",
  "speed|frost": "Wind Chill",
  "speed|impact": "Bulldozer Boost",
  "speed|turret": "Strafing Run",
  "speed|vortex": "Slipstream Maw",
  "speed|graze": "Daredevil Dash",
  "speed|ram": "Meteor Tackle",
  "magnet|magnet": "Event Horizon",
  "magnet|slow": "Gravity Well",
  "magnet|bomb": "Molten Lodestone",
  "magnet|rear": "Tractor Wake",
  "magnet|side": "Lodestone Wings",
  "magnet|arc": "Static Salvage",
  "magnet|cull": "Reaper's Tithe",
  "magnet|velocity": "Gauss Accelerator",
  "magnet|thorns": "Static Cling",
  "magnet|armor": "Lodestone Mail",
  "magnet|dodge": "Phantom Attractor",
  "magnet|scavenger": "Loot Lodestone",
  "magnet|greed": "Gold Rush",
  "magnet|adrenaline": "Loot Rush",
  "magnet|shrink": "Pocket Singularity",
  "magnet|drones": "Salvage Squadron",
  "magnet|missiles": "Tractor Salvo",
  "magnet|mortar": "Prospector's Blast",
  "magnet|boom": "Loot Detonator",
  "magnet|frost": "Polar Attraction",
  "magnet|impact": "Polarity Shift",
  "magnet|turret": "Mining Rig",
  "magnet|vortex": "Event Horizon",
  "magnet|graze": "Windfall Drift",
  "magnet|ram": "Collision Course",
  "slow|slow": "Event Horizon",
  "slow|bomb": "Tar Pit",
  "slow|rear": "Undertow Volley",
  "slow|side": "Quagmire Crossfire",
  "slow|arc": "Lightning Tarpit",
  "slow|cull": "Dead Air",
  "slow|velocity": "Time Dilation",
  "slow|thorns": "Bramble Bog",
  "slow|armor": "Stonewall Stasis",
  "slow|dodge": "Time Slip",
  "slow|scavenger": "Mercy Mire",
  "slow|greed": "Time Is Money",
  "slow|adrenaline": "Bullet Time",
  "slow|shrink": "Storm's Eye",
  "slow|drones": "Tarpit Escort",
  "slow|missiles": "Sitting Ducks",
  "slow|mortar": "Quagmire Shells",
  "slow|boom": "Minefield Mire",
  "slow|frost": "Absolute Zero",
  "slow|impact": "Undertow",
  "slow|turret": "Suppression Grid",
  "slow|vortex": "Quicksand Rift",
  "slow|graze": "Bullet Waltz",
  "slow|ram": "Steamroller",
  "bomb|bomb": "Everburn",
  "bomb|rear": "Scorched Wake",
  "bomb|side": "Flanking Inferno",
  "bomb|arc": "Plasma Storm",
  "bomb|cull": "Funeral Pyre",
  "bomb|velocity": "Comet Barrage",
  "bomb|thorns": "Backdraft",
  "bomb|armor": "Furnace Mail",
  "bomb|dodge": "Will-o'-Wisp",
  "bomb|scavenger": "Phoenix Harvest",
  "bomb|greed": "Money to Burn",
  "bomb|adrenaline": "Flashpoint Fury",
  "bomb|shrink": "Ember Wisp",
  "bomb|drones": "Firefly Squadron",
  "bomb|missiles": "Napalm Seekers",
  "bomb|mortar": "Napalm Rain",
  "bomb|boom": "Firestorm Payload",
  "bomb|frost": "Thermal Shock",
  "bomb|impact": "Napalm Slam",
  "bomb|turret": "Pyre Sentinels",
  "bomb|vortex": "Inferno Maelstrom",
  "bomb|graze": "Playing With Fire",
  "bomb|ram": "Fireball Charge",
  "rear|rear": "Scorpion's Tail",
  "rear|side": "Crossfire Compass",
  "rear|arc": "Thunder Tail",
  "rear|cull": "Death From Behind",
  "rear|velocity": "Parthian Shot",
  "rear|thorns": "Scorched Retreat",
  "rear|armor": "Covered Retreat",
  "rear|dodge": "Matador's Farewell",
  "rear|scavenger": "Vulture's Wake",
  "rear|greed": "Bounty Backfire",
  "rear|adrenaline": "Fighting Retreat",
  "rear|shrink": "Slipstream Sting",
  "rear|drones": "Tailgunner Wing",
  "rear|missiles": "Parthian Warheads",
  "rear|mortar": "Parting Gift",
  "rear|boom": "Scorched Retreat",
  "rear|frost": "Icy Exhaust",
  "rear|impact": "Mule Kick",
  "rear|turret": "Covering Fire",
  "rear|vortex": "Riptide Wake",
  "rear|graze": "Daredevil Retreat",
  "rear|ram": "Rearview Rampage",
  "side|side": "Full Broadside",
  "side|arc": "Tesla Broadside",
  "side|cull": "Flanking Guillotine",
  "side|velocity": "Slipstream Flank",
  "side|thorns": "Bristling Broadside",
  "side|armor": "Ironclad Broadside",
  "side|dodge": "Matador's Volley",
  "side|scavenger": "Bountiful Broadside",
  "side|greed": "Privateer Volley",
  "side|adrenaline": "Flanking Frenzy",
  "side|shrink": "Slim Broadside",
  "side|drones": "Wingman Array",
  "side|missiles": "Rocket Flanks",
  "side|mortar": "Artillery Wings",
  "side|boom": "Broadside Blitz",
  "side|frost": "Sleet Crossfire",
  "side|impact": "Concussive Flanks",
  "side|turret": "Gunwale Garrison",
  "side|vortex": "Whirlpool Wings",
  "side|graze": "Razor Flanks",
  "side|ram": "Broadside Brawler",
  "arc|arc": "Perfect Storm",
  "arc|cull": "Judgment Bolt",
  "arc|velocity": "Thunderbolt",
  "arc|thorns": "Static Vengeance",
  "arc|armor": "Faraday Plate",
  "arc|dodge": "Lightning Reflexes",
  "arc|scavenger": "Static Salvage",
  "arc|greed": "Golden Conduit",
  "arc|adrenaline": "Livewire Rush",
  "arc|shrink": "Static Wisp",
  "arc|drones": "Tesla Swarm",
  "arc|missiles": "Lightning Warheads",
  "arc|mortar": "Thunderclap Shells",
  "arc|boom": "Thunderclap",
  "arc|frost": "Cryoshock",
  "arc|impact": "Thunderclap",
  "arc|turret": "Tesla Battery",
  "arc|vortex": "Tempest Maw",
  "arc|graze": "Live Wire",
  "arc|ram": "Galvanic Charge",
  "cull|cull": "Reaper's Decree",
  "cull|velocity": "Swift Verdict",
  "cull|thorns": "Martyr's Guillotine",
  "cull|armor": "Iron Reaper",
  "cull|dodge": "Phantom Headsman",
  "cull|scavenger": "Mercy Harvest",
  "cull|greed": "Bounty Hunter",
  "cull|adrenaline": "Killing Frenzy",
  "cull|shrink": "Pocket Guillotine",
  "cull|drones": "Firing Squad",
  "cull|missiles": "Headhunter Warheads",
  "cull|mortar": "Killing Field",
  "cull|boom": "Final Detonation",
  "cull|frost": "Cold Guillotine",
  "cull|impact": "Knockout Blow",
  "cull|turret": "Firing Squad",
  "cull|vortex": "Abattoir Rift",
  "cull|graze": "Death's Whisper",
  "cull|ram": "Reaper's Rush",
  "velocity|velocity": "Railgun",
  "velocity|thorns": "Railgun Reprisal",
  "velocity|armor": "Plated Slipstream",
  "velocity|dodge": "Slipshot",
  "velocity|scavenger": "Swift Spoils",
  "velocity|greed": "Bullet Bullion",
  "velocity|adrenaline": "Redline Surge",
  "velocity|shrink": "Hypersonic Gnat",
  "velocity|drones": "Strafing Escort",
  "velocity|missiles": "Hypersonic Swarm",
  "velocity|mortar": "Sonic Shellburst",
  "velocity|boom": "Cannonball Express",
  "velocity|frost": "Cryo Slugs",
  "velocity|impact": "Freight Train Rounds",
  "velocity|turret": "Railgun Nest",
  "velocity|vortex": "Riptide Rounds",
  "velocity|graze": "Slipstream Shot",
  "velocity|ram": "Ballistic Charge",
  "thorns|thorns": "Iron Maiden",
  "thorns|armor": "Molten Plating",
  "thorns|dodge": "Matador's Sting",
  "thorns|scavenger": "Bramble Bounty",
  "thorns|greed": "Pain Dividend",
  "thorns|adrenaline": "Pain Engine",
  "thorns|shrink": "Sea Urchin",
  "thorns|drones": "Bramble Escort",
  "thorns|missiles": "Spiteful Swarm",
  "thorns|mortar": "Napalm Bramble",
  "thorns|boom": "Vengeful Payload",
  "thorns|frost": "Hoarfrost Hide",
  "thorns|impact": "Porcupine Slam",
  "thorns|turret": "Bramble Battery",
  "thorns|vortex": "Briar Maelstrom",
  "thorns|graze": "Barbed Halo",
  "thorns|ram": "Porcupine Charge",
  "armor|armor": "Dreadnought",
  "armor|dodge": "Phantom Plating",
  "armor|scavenger": "Carrion Plating",
  "armor|greed": "Gilded Plate",
  "armor|adrenaline": "Berserker Plating",
  "armor|shrink": "Pocket Fortress",
  "armor|drones": "Armada Aegis",
  "armor|missiles": "Siegebreaker",
  "armor|mortar": "Siege Plating",
  "armor|boom": "Blastproof Rounds",
  "armor|frost": "Rimeguard",
  "armor|impact": "Iron Piledriver",
  "armor|turret": "Pillbox Protocol",
  "armor|vortex": "Crushing Depths",
  "armor|graze": "Nerve of Steel",
  "armor|ram": "Bulldozer Plating",
  "dodge|dodge": "Untouchable",
  "dodge|scavenger": "Graverobber's Grace",
  "dodge|greed": "Gambler's Grace",
  "dodge|adrenaline": "Matador's Fury",
  "dodge|shrink": "Vanishing Point",
  "dodge|drones": "Decoy Squadron",
  "dodge|missiles": "Sidewinder Slip",
  "dodge|mortar": "Blur Bombardment",
  "dodge|boom": "Blink Bomber",
  "dodge|frost": "Cold Shoulder",
  "dodge|impact": "Sidestep Slam",
  "dodge|turret": "Decoy Battery",
  "dodge|vortex": "Slipstream Rift",
  "dodge|graze": "Matador",
  "dodge|ram": "Matador's Horns",
  "scavenger|scavenger": "Carrion King",
  "scavenger|greed": "Dragon's Hoard",
  "scavenger|adrenaline": "Feeding Frenzy",
  "scavenger|shrink": "Mousehole Medic",
  "scavenger|drones": "Carrion Flock",
  "scavenger|missiles": "Vulture Strike",
  "scavenger|mortar": "Carrion Crater",
  "scavenger|boom": "Salvage Detonator",
  "scavenger|frost": "Frozen Spoils",
  "scavenger|impact": "Vulture Uppercut",
  "scavenger|turret": "Vulture Nest",
  "scavenger|vortex": "Carrion Cyclone",
  "scavenger|graze": "Risk Harvest",
  "scavenger|ram": "Roadkill Rations",
  "greed|greed": "Midas Touch",
  "greed|adrenaline": "Blood Money",
  "greed|shrink": "Pocket Fortune",
  "greed|drones": "Fortune Fleet",
  "greed|missiles": "Fortune Seekers",
  "greed|mortar": "Jackpot Barrage",
  "greed|boom": "Golden Fireworks",
  "greed|frost": "Frozen Assets",
  "greed|impact": "Smash and Grab",
  "greed|turret": "Golden Garrison",
  "greed|vortex": "Avarice Maelstrom",
  "greed|graze": "High Roller",
  "greed|ram": "Smash and Grab",
  "adrenaline|adrenaline": "Berserk Overdrive",
  "adrenaline|shrink": "Hornet's Pulse",
  "adrenaline|drones": "Frenzy Flock",
  "adrenaline|missiles": "Retaliation Salvo",
  "adrenaline|mortar": "Panic Bombardment",
  "adrenaline|boom": "Rage Detonation",
  "adrenaline|frost": "Cold Fury",
  "adrenaline|impact": "Counterpunch",
  "adrenaline|turret": "Rage Battery",
  "adrenaline|vortex": "Frenzied Riptide",
  "adrenaline|graze": "Death Wish",
  "adrenaline|ram": "Berserker Charge",
  "shrink|shrink": "Vanishing Point",
  "shrink|drones": "Gnat Squadron",
  "shrink|missiles": "Mosquito Barrage",
  "shrink|mortar": "Pocket Artillery",
  "shrink|boom": "Pocket Nuke",
  "shrink|frost": "Snowflake Dance",
  "shrink|impact": "Featherweight Punch",
  "shrink|turret": "Gnat's Nest",
  "shrink|vortex": "Pocket Singularity",
  "shrink|graze": "Needle's Eye",
  "shrink|ram": "Bee Sting",
  "drones|drones": "Sovereign Swarm",
  "drones|missiles": "Strike Squadron",
  "drones|mortar": "Bombardier Wing",
  "drones|boom": "Bomber Squadron",
  "drones|frost": "Blizzard Wing",
  "drones|impact": "Wingman Wallop",
  "drones|turret": "Robot Uprising",
  "drones|vortex": "Riftwing Escort",
  "drones|graze": "Wingman's Luck",
  "drones|ram": "Kamikaze Wingmen",
  "missiles|missiles": "Armageddon Swarm",
  "missiles|mortar": "Cluster Seekers",
  "missiles|boom": "Doomsday Payload",
  "missiles|frost": "Permafrost Payload",
  "missiles|impact": "Concussive Payload",
  "missiles|turret": "Silo Sentinels",
  "missiles|vortex": "Black Hole Barrage",
  "missiles|graze": "Danger-Close Payload",
  "missiles|ram": "Kamikaze Payload",
  "mortar|mortar": "Carpet Bombing",
  "mortar|boom": "Carpet Bombing",
  "mortar|frost": "Frostfall Artillery",
  "mortar|impact": "Shockwave Shells",
  "mortar|turret": "Artillery Outpost",
  "mortar|vortex": "Crater Maw",
  "mortar|graze": "Shockwave Skimmer",
  "mortar|ram": "Crash Crater",
  "boom|boom": "Megaton Payload",
  "boom|frost": "Shatterfrost",
  "boom|impact": "Shockwave Slugs",
  "boom|turret": "Claymore Sentry",
  "boom|vortex": "Collapsing Star",
  "boom|graze": "Powder Keg Tango",
  "boom|ram": "Demolition Derby",
  "frost|frost": "Absolute Zero",
  "frost|impact": "Avalanche Slugs",
  "frost|turret": "Cryo Sentry",
  "frost|vortex": "Blizzard Maw",
  "frost|graze": "Frostbite Waltz",
  "frost|ram": "Icebreaker",
  "impact|impact": "Unstoppable Force",
  "impact|turret": "Concussive Sentry",
  "impact|vortex": "Gravity Hammer",
  "impact|graze": "Brushback Pitch",
  "impact|ram": "Wrecking Ball",
  "turret|turret": "Firebase Omega",
  "turret|vortex": "Riftside Battery",
  "turret|graze": "Danger Close",
  "turret|ram": "Battering Bastion",
  "vortex|vortex": "Event Horizon",
  "vortex|graze": "Edge of Oblivion",
  "vortex|ram": "Undertow Tackle",
  "graze|graze": "Stormdancer",
  "graze|ram": "Kiss of Steel",
  "ram|ram": "Unstoppable Force",
};
window.FUSION_NAMES = FUSION_NAMES;
